/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline_reservation_systems;


import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Nour waled
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        close_button = new javax.swing.JButton();
        login_label = new javax.swing.JLabel();
        InputName = new javax.swing.JTextField();
        InputPass = new javax.swing.JPasswordField();
        InputDate = new javax.swing.JTextField();
        InputEmail = new javax.swing.JTextField();
        InputCountry = new javax.swing.JTextField();
        InputMobile = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        LastName = new javax.swing.JTextField();
        UserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        close_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\mE\\Documents\\Level4Term1\\Airline_Reservation_Systems\\Airline reservation systems\\src\\airline_reservation_systems\\images\\close.png")); // NOI18N
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });

        login_label.setFont(new java.awt.Font("Andalus", 1, 48)); // NOI18N
        login_label.setForeground(new java.awt.Color(0, 118, 221));
        login_label.setText("Create Account");

        InputName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InputName.setForeground(new java.awt.Color(0, 118, 221));
        InputName.setText("First Name");
        InputName.setToolTipText("");
        InputName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        InputName.setName(""); // NOI18N
        InputName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputNameFocusLost(evt);
            }
        });
        InputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNameActionPerformed(evt);
            }
        });

        InputPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InputPass.setForeground(new java.awt.Color(0, 118, 221));
        InputPass.setText("Enter Your Password");
        InputPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputPassFocusLost(evt);
            }
        });

        InputDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InputDate.setForeground(new java.awt.Color(0, 118, 221));
        InputDate.setText("Date Of Birth");
        InputDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputDateFocusLost(evt);
            }
        });
        InputDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDateActionPerformed(evt);
            }
        });

        InputEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InputEmail.setForeground(new java.awt.Color(0, 118, 221));
        InputEmail.setText("E-mail");
        InputEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputEmailFocusLost(evt);
            }
        });
        InputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEmailActionPerformed(evt);
            }
        });

        InputCountry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InputCountry.setForeground(new java.awt.Color(0, 118, 221));
        InputCountry.setText("Country of residence");
        InputCountry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputCountryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputCountryFocusLost(evt);
            }
        });
        InputCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCountryActionPerformed(evt);
            }
        });

        InputMobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InputMobile.setForeground(new java.awt.Color(0, 118, 221));
        InputMobile.setText("Mobile");
        InputMobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputMobileFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputMobileFocusLost(evt);
            }
        });
        InputMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputMobileActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 118, 221));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline_reservation_systems/images/login.png"))); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 118, 221));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mE\\Documents\\Level4Term1\\Airline_Reservation_Systems\\Airline reservation systems\\src\\airline_reservation_systems\\images\\login.png")); // NOI18N
        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        LastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LastName.setForeground(new java.awt.Color(0, 118, 221));
        LastName.setText("Last Name");
        LastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LastNameFocusLost(evt);
            }
        });
        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });

        UserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserName.setForeground(new java.awt.Color(0, 118, 221));
        UserName.setText("User Name");
        UserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserNameFocusLost(evt);
            }
        });
        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(close_button)
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserName)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(31, 31, 31))
                    .addComponent(InputName)
                    .addComponent(login_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InputPass)
                    .addComponent(InputDate)
                    .addComponent(InputEmail)
                    .addComponent(InputCountry)
                    .addComponent(InputMobile)
                    .addComponent(LastName))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close_button)
                    .addComponent(login_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InputPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InputDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InputCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InputMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 99, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mE\\Documents\\Level4Term1\\Airline_Reservation_Systems\\Airline reservation systems\\src\\airline_reservation_systems\\images\\Airplane4.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        // TODO add your handling code here:
        int a =JOptionPane.showConfirmDialog(null,"Do You Really Want To Exit Application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_close_buttonActionPerformed

    private void InputNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputNameFocusGained
        // TODO add your handling code here:
        if(InputName.getText().equals("First Name")){
            InputName.setText("");
            InputName.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_InputNameFocusGained

    private void InputNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputNameFocusLost
        // TODO add your handling code here:
        if(InputName.getText().equals("")){
            InputName.setText("First Name");
            InputName.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_InputNameFocusLost

    private void InputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNameActionPerformed

    private void InputPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputPassFocusGained
        // TODO add your handling code here:
        if(InputPass.getText().equals("Enter Your Password")){
            InputPass.setText("");
            InputPass.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_InputPassFocusGained

    private void InputPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputPassFocusLost
        // TODO add your handling code here:
        if(InputPass.getText().equals("")){
            InputPass.setText("Enter Your Password");
            InputPass.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_InputPassFocusLost

    private void InputDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputDateFocusGained
        // TODO add your handling code here:
        if(InputDate.getText().equals("Date Of Birth")){
            InputDate.setText("");
            InputDate.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_InputDateFocusGained

    private void InputDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputDateFocusLost
        // TODO add your handling code here:
        if(InputDate.getText().equals("")){
            InputDate.setText("Date Of Birth");
            InputDate.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_InputDateFocusLost

    private void InputDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDateActionPerformed

    private void InputEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputEmailFocusGained
        // TODO add your handling code here:
        if(InputEmail.getText().equals("E-mail")){
            InputEmail.setText("");
            InputEmail.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_InputEmailFocusGained

    private void InputEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputEmailFocusLost
        // TODO add your handling code here:
        if(InputEmail.getText().equals("")){
            InputEmail.setText("E-mail");
            InputEmail.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_InputEmailFocusLost

    private void InputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputEmailActionPerformed

    private void InputCountryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputCountryFocusGained
        // TODO add your handling code here:
        if(InputCountry.getText().equals("Country of residence")){
            InputCountry.setText("");
            InputCountry.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_InputCountryFocusGained

    private void InputCountryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputCountryFocusLost
        // TODO add your handling code here:
        if(InputCountry.getText().equals("")){
            InputCountry.setText("Country of residence");
            InputCountry.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_InputCountryFocusLost

    private void InputCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputCountryActionPerformed

    private void InputMobileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputMobileFocusGained
        // TODO add your handling code here:
        if(InputMobile.getText().equals("Mobile")){
            InputMobile.setText("");
            InputMobile.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_InputMobileFocusGained

    private void InputMobileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputMobileFocusLost
        // TODO add your handling code here:
        if(InputMobile.getText().equals("")){
            InputMobile.setText("Mobile");
            InputMobile.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_InputMobileFocusLost

    private void InputMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputMobileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
      Login log = new Login();
      log.setTitle("LogIn Form");
      log.setVisible(true);
      log.setResizable(false);
      this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void LastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastNameFocusGained
        // TODO add your handling code here:
        if(LastName.getText().equals("Last Name")){
            LastName.setText("");
            LastName.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_LastNameFocusGained

    private void LastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastNameFocusLost
        // TODO add your handling code here:
        if(LastName.getText().equals("")){
            LastName.setText("Last Name");
            LastName.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_LastNameFocusLost

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed

    private void UserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserNameFocusGained
        // TODO add your handling code here:
        if(UserName.getText().equals("User Name")){
            UserName.setText("");
            UserName.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_UserNameFocusGained

    private void UserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserNameFocusLost
        // TODO add your handling code here:
        if(UserName.getText().equals("")){
            UserName.setText("User Name");
            UserName.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_UserNameFocusLost

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       User user =new User();
       if(!(InputName.getText().equals("First Name") || LastName.getText().equals("Last Name") || UserName.getText().equals("User Name") || InputPass.getText().equals("Enter Your Password") ||
            InputDate.getText().equals("Date Of Birth") || InputEmail.getText().equals("E-mail") || InputCountry.getText().equals("Country of residence") || InputMobile.getText().equals("Mobile"))){
        if(!user.checkUsername(UserName.getText())){
          if(user.CheckRegistration(InputName.getText() ,LastName.getText(),UserName.getText() ,InputPass.getText() , 
            InputDate.getText(),InputEmail.getText(),InputCountry.getText() ,InputMobile.getText())){
          
            JOptionPane.showMessageDialog(null,"Register Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
             Reservation res = new Reservation(UserName.getText());
             res.setTitle("Reservation Form");
             res.setVisible(true);
             res.setResizable(false);
             this.dispose();
        }
          else {
            JOptionPane.showMessageDialog(null,"Failed Register","Error",JOptionPane.ERROR_MESSAGE);
          }
        }
        else {
             JOptionPane.showMessageDialog(null,"Username already exist ,Please Choose another Username","Error",JOptionPane.ERROR_MESSAGE);
            
        } }
       else {
            JOptionPane.showMessageDialog(null,"Please Fill All ","Error",JOptionPane.ERROR_MESSAGE);
       }   
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputCountry;
    private javax.swing.JTextField InputDate;
    private javax.swing.JTextField InputEmail;
    private javax.swing.JTextField InputMobile;
    private javax.swing.JTextField InputName;
    private javax.swing.JPasswordField InputPass;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField UserName;
    private javax.swing.JButton close_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel login_label;
    // End of variables declaration//GEN-END:variables
}
